language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
jobs:  
  include:
    - stage: build                # naming the Build state
      name: "Build"            
      script: npm run build
    - stage: test
      name: "Unit Tests"
      script: npm test
stages:
  - build
  - test