export const ACTIONTYPES = {
    NOTIFICATION_START_WAITING: "NOTIFICATION_START_WAITING",
    NOTIFICATION_STOP_WAITING: "NOTIFICATION_STOP_WAITING",
    GET_WALLET: "GET_WALLET",
    CLOSE_WALLET: "CLOSE_WALLET",
    GET_DASHBOARD: "GET_DASHBOARD"
};