export const ACTIONTYPES = {
    NOTIFICATION_START_WAITING: "NOTIFICATION_START_WAITING",
    NOTIFICATION_STOP_WAITING: "NOTIFICATION_STOP_WAITING",
    GET_WALLET: "GET_WALLET",
    CLOSE_WALLET: "CLOSE_WALLET",
    GET_DASHBOARD: "GET_DASHBOARD",
    GET_TRANSCATIONS: "GET_TRANSCATIONS",
    GET_RECEIPT: "GET_RECEIPT",
    NAVIGATION_CHANGE: "NAVIGATION_CHANGE",
    GET_NOTIFICATION_ALERTS: "GET_NOTIFICATION_ALERTS"
};